
trigger:
- main

pool: Laptop-pool

steps:
- script: echo K8s Terraform
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publicKey
  inputs:
    secureFile: 'id_rsa.pub'
- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    # commandOptions: '-var client_id=$(client_id) -var client_secret=$(client-secret) -var ssh_public_keys=$(publicKey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'arm-service-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageaccountaadii82100'
    backendAzureRmContainerName: 'storageaccountaadii'
    backendAzureRmKey: 'kubernetesdev.tfstate'
    allowTelemetryCollection: true

- task: TerraformCLI@2
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    environmentServiceName: 'arm-service-connection'
    commandOptions: '-lock=false -var client_id=$(client_id) -var client_secret=$(client-secret) -var ssh_public_key=$(publicKey.secureFilePath)'
# - task: TerraformCLI@2
#   inputs:
#     command: 'apply'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
#     environmentServiceName: 'arm-service-connection'
#     runAzLogin: true
#     commandOptions: '-var client_id=$(client_id) -var client_secret=$(client-secret)'
#     allowTelemetryCollection: false

   